GeoscienceAustralia/amazonia

- .pullapprove.yml
http://docs.pullapprove.com/yaml/
> Auto-556 Adding Pull Approve yml file

- amazonia/amz.py
Changing paths to amz to be relative for tests
BUILD PASSING: https://gaautobots.atlassian.net/builds/browse/PIPE-AT73-3
> Dev sys stack create auto 510 fudd

- README.md
updated readme to show amz.py options and our preference to merge changes to integration branch
> AUTO-565 readme.md updates

- CHANGELOG.md
- amazonia/amz.py
- test/sys_tests/test_sys_stack_create.py
Refactored system stack test to allow for different yaml files to be passed in to allow for different tests.
Used code from amz.py
Updated changelog.md
BUILD Passing https://gaautobots.atlassian.net/builds/browse/AM-AST11-8
> Updated System Stack Create tests 

- CHANGELOG.md
- amazonia/classes/s3.py
- setup.py
- sonar-project.properties
- test/sys_tests/test_sys_s3.py
- test/unit_tests/test_s3.py
Build Passing 
https://gaautobots.atlassian.net/builds/browse/AM-AUT12-4
> Adding s3 bucket, sys test and unit test

- amazonia/schema.yaml
- test/unit_tests/test_yaml.py
- test/unit_tests/test_yaml_complete_valid.yaml
- Minsize, Maxsize number/string type,
- SNS notification list of strings,
- Updated unit tests to reflect SNS notification type change
Build passing:
https://gaautobots.atlassian.net/builds/browse/AM-AUT14
> AUTO-593, AUTO-597 Cerberus schema changes

- CHANGELOG.md
- setup.py
- sonar-project.properties
Incrementing version to 1.0.4, documenting change in changelog
Build Passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT15
> Incrementing version to 1.0.4, documenting change in changelog

- .bumpversion.cfg
Adding config required for bumpversion
> AUTO-603 Creating .bumpversion.cfg

- CHANGELOG.md
- amazonia/classes/yaml.py
Build passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT18-1
feel free to delete branch once merged :)
> AUTO-621 Fixing code linting issues from sonarqube

- CHANGELOG.md
- test/sys_tests/test_sys_stack_create.py
Adding extra conditions for create and delete stack
**PASSING BUILD (UNIT)** https://gaautobots.atlassian.net/builds/browse/AM-AUT21-2
**PLEASE CHECK BUILD (SYSTEMS)** https://gaautobots.atlassian.net/builds/browse/AM-SYS3-1
> Adding created and delete failed conditions to create_and_delete_stack()

- test/unit_tests/test_elb.py
Adding back required re and adding pycharm hint
> Adding back required re and adding pycharm hint

- CHANGELOG.md
- amazonia/classes/kms.py
- test/sys_tests/test_sys_kms.py
- test/unit_tests/test_kmskey.py
Adding doco, unit tests, systems test for KMS to create a file
**BUILD PASSING** - https://gaautobots.atlassian.net/builds/browse/AM-AUT27-10
> Creating KMS Key Class

- CHANGELOG.md
- amazonia/classes/dynamo_db.py
- amazonia/classes/kms.py
- test/sys_tests/test_sys_dynamo_db.py
- test/unit_tests/test_dynamo_db.py
> Dynamodb Class with unit tests and systems tests Auto-649

- CHANGELOG.md
- amazonia/classes/cloudtrail.py
**BUILD PASSES**  But I hvae deleted the plan already as part of the release automation reconstruction.
> Updating 'DependsOn' so it exists inside cloudtrail troposphere function

- CHANGELOG.md
- amazonia/classes/database_unit.py
- amazonia/classes/dynamo_db.py
- amazonia/classes/stack.py
- amazonia/defaults.yaml
- amazonia/schema.yaml
- test/sys_tests/test_sys_database_unit.py
- test/sys_tests/test_sys_stack.py
- test/unit_tests/test_cloudtrail.py
- test/unit_tests/test_database_unit.py
- test/unit_tests/test_stack.py
Adding new DB params hdd_size and snapshot_id
Updated unit tests
Updated schema and yaml files
Fixed imports in test_cloudtrail
Removing extra brackets from dynamo_db class
Build passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT34
> AUTO-659 RDS snapshot id and hdd size

- amazonia/classes/cloudtrail.py
- amazonia/classes/dynamo_db.py
Added Doc for DynamoDB
Added Doc for CloudTrail
> DynamoDB and CloudTrail Doco

- CHANGELOG.md
- amazonia/classes/autoscaling_unit.py
- amazonia/classes/security_enabled_object.py
- test/unit_tests/test_autoscaling_unit.py
Passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT39-4
> Auto-672 Update rules to allow 0-65535 between NAT and ASG's

- amazonia/classes/credstash.py
- amazonia/classes/dynamo_db.py
- amazonia/classes/kms.py
- test/sys_tests/test_sys_credstash.py
- test/unit_tests/test_credstash.py
- test/unit_tests/test_kmskey.py
**BUILD PASSING** https://gaautobots.atlassian.net/builds/browse/AM-AUT37/latest
> Credstash Class, Unit Tests and Systems Test

- CHANGELOG.md
- amazonia/classes/hosted_zone.py
- amazonia/classes/stack.py
- test/sys_tests/test_sys_hosted_zone.py
- test/unit_tests/test_hosted_zone.py
* Added hostedzone class
* Tests for the above
* Updated stack class to create a VPC that can support private hosted zones.
Passing build: https://gaautobots.atlassian.net/builds/browse/AM-AUT36-2
> AUTO-609 Add public and private hostedzone support.

- CHANGELOG.md
- test/sys_tests/test_sys_credstash.py
- test/unit_tests/test_credstash.py
**BUILD PASSING** - https://gaautobots.atlassian.net/builds/browse/AM-AUT41/latest
> Ddb_attributes added to credstash systems tests

- CHANGELOG.md
- amazonia/classes/single_instance.py
- amazonia/classes/sns.py
- amazonia/classes/stack.py
- amazonia/classes/yaml.py
- amazonia/defaults.yaml
- amazonia/schema.yaml
- test/sys_tests/test_sys_single_jump.py
- test/sys_tests/test_sys_single_nat.py
- test/sys_tests/test_sys_sns.py
- test/unit_tests/test_autoscaling_unit.py
- test/unit_tests/test_single_instance.py
- test/unit_tests/test_sns.py
- test/unit_tests/test_stack.py
- test/unit_tests/test_yaml_complete_valid.yaml
Build Passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT43/latest
> AUTO-646 - Cloudwatch alerting on NAT instances

- CHANGELOG.md
- amazonia/classes/hosted_zone.py
- amazonia/classes/single_instance.py
- test/unit_tests/test_security_enabled_object.py
Build Passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT45/latest
> AUTO-684 - updated code to fix coverage and issues flagged in sonarqube

- CHANGELOG.md
- amazonia/classes/yaml.py
- amazonia/schema.yaml
Passing Build: https://gaautobots.atlassian.net/builds/browse/AM-AUT47/latest
> AUTO-686 - Corrected database_unit values handling from application yaml

- .pullapprove.yml
- CHANGELOG.md
Passing build: https://gaautobots.atlassian.net/builds/browse/AM-AUT46/latest
Added James Kingsmill to .pullapprove.yml
> AUTO-685 - Added James Kingsmill to list of pull approvers

- CHANGELOG.md
- test/unit_tests/test_database_unit.py
Passing build: https://gaautobots.atlassian.net/builds/browse/AM-AUT49/latest
> Update DB unit test with working instance type AUTO-690

- .pullapprove.yml
- CHANGELOG.md
Build passing - https://gaautobots.atlassian.net/builds/browse/AM-AUT50/latest
> Added Angelo to pull approve AUTO-685

- CHANGELOG.md
Create changelog to reflect the zd and config object changes.
> Updated Changelog for version 1.1.0

- CHANGELOG.md
- amazonia/classes/database_config.py
- amazonia/classes/database_unit.py
- amazonia/classes/yaml.py
- amazonia/defaults.yaml
- amazonia/schemas/cerberus_schema.yaml
- test/sys_tests/test_sys_database_unit.py
- test/unit_tests/test_database_unit.py
- test/unit_tests/test_stack.py
Adding db_snapshot_id, db_backup_window, db_backup_retention, db_maintenance_window, db_storage_type to db unit
Build Passing - https://gaautobots.atlassian.net/builds/browse/AM-AUT52/latest
> New db unit properties Auto-715

- CHANGELOG.md
- amazonia/classes/zd_autoscaling_unit.py
- test/sys_tests/test_sys_stack.py
- test/unit_tests/test_stack.py
- Removing unused zd state exception
- Minor fixes to stack unit tests and stack system tests to reflect changes to zd and db config
- Code formatting
Build passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT55
> Fixing system tests, fixing sonarqube problems

- CHANGELOG.md
- amazonia/application.yaml
- amazonia/classes/database_unit.py
Also removing DBName when passing in snapshot id
Build Passing = https://gaautobots.atlassian.net/builds/browse/AM-AUT58/latest
> Updateing DBInstance to DB Unit

- CHANGELOG.md
- amazonia/classes/asg.py
- amazonia/classes/autoscaling_unit.py
- amazonia/classes/elb.py
- amazonia/classes/stack.py
- amazonia/classes/zd_autoscaling_unit.py
- test/sys_tests/test_sys_asg.py
- test/sys_tests/test_sys_autoscaling_unit.py
- test/sys_tests/test_sys_block_devices.py
- test/sys_tests/test_sys_database_unit.py
- test/sys_tests/test_sys_elb.py
- test/sys_tests/test_sys_hosted_zone.py
- test/sys_tests/test_sys_zd_autoscaling_unit.py
- test/unit_tests/test_asg.py
- test/unit_tests/test_database_unit.py
Updating:
amazonia/classes/asg.py
amazonia/classes/autoscaling_unit.py
amazonia/classes/elb.py
amazonia/classes/stack.py
amazonia/classes/zd_autoscaling_unit.py
Removing ASG DependsOn Nat to inside the ASG object rather than outside at the unit level.
Updating Unit tests and Systems Tests
Passing Build: https://gaautobots.atlassian.net/builds/browse/AM-AUT63/latest
> Adding DependsOn inside the resource AUTO-642

- CHANGELOG.md
- amazonia/classes/database_unit.py
To be in line with CF terminology
> Adding master as prefix for db parameters AUTO-751

- amazonia/classes/yaml.py
- amazonia/schemas/cerberus_schema.yaml
- test/unit_tests/test_yaml.py
Change Cerberus  ValidationError to Amazonia InvalidYamlValueError
> Cereberus Update Auto-786

- CHANGELOG.md
- amazonia/classes/stack.py
- test/unit_tests/test_stack.py
Passing Build: https://gaautobots.atlassian.net/builds/browse/AM-AUT74/latest
> Renaming PubRT and PriRT explicitely to PubRouteTable and PriRouteTable AUTO-801

- CHANGELOG.md
- amazonia/classes/api_gateway_config.py
- amazonia/classes/api_gateway_unit.py
- amazonia/classes/yaml_fields.py
- amazonia/defaults.yaml
- amazonia/schemas/cerberus_schema.yaml
- test/sys_tests/test_sys_api_gateway.py
- test/unit_tests/test_api_gateway.py
- test/unit_tests/test_stack.py
- test/unit_tests/test_yaml_complete_valid.yaml
Passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT73/latest
Passing: https://gaautobots.atlassian.net/builds/browse/AM-AST67/latest
> AUTO-799 Added add unit flow function to Api Gateway class to enable lambda unit integration.

- CHANGELOG.md
- amazonia/classes/cf_cache_behavior_config.py
- amazonia/classes/cf_distribution_config.py
- amazonia/classes/cf_distribution_unit.py
- amazonia/classes/yaml_fields.py
- amazonia/defaults.yaml
- amazonia/schemas/cerberus_schema.yaml
- test/sys_tests/test_sys_cfdistribution.py
- test/unit_tests/test_cf_distribution.py
- test/unit_tests/test_stack.py
- test/unit_tests/test_yaml_complete_valid.yaml
Merge default cache behavior/additional cache behaviors into a single class
Use new variable is_default to differentiate the two types
> AUTO-765 Refactor Cloudfront implementation

- amazonia/schemas/cerberus_schema.yaml
Set new ELB config items to nullable in schema
> Set new ELB config items to nullable in schema

- test/unit_tests/test_yaml_bad_defaults.yaml
> Remove deprecated CF values from bad defaults yaml

- CHANGELOG.md
- amazonia/classes/elb.py
- amazonia/classes/elb_config.py
- amazonia/classes/elb_listeners_config.py
- amazonia/classes/yaml_fields.py
- amazonia/defaults.yaml
- amazonia/schemas/cerberus_schema.yaml
- test/sys_tests/test_sys_autoscaling_unit.py
- test/sys_tests/test_sys_elb.py
- test/sys_tests/test_sys_stack.py
- test/unit_tests/test_autoscaling_unit.py
- test/unit_tests/test_elb.py
- test/unit_tests/test_stack.py
- test/unit_tests/test_yaml_complete_valid.yaml
- test/unit_tests/test_zd_autoscaling_unit.py
- Patched sticky cookie config to be in listeners
- Adding stick app cookies to yaml complete valid test (mmm sticky app cookies)
- Updating changelog for sticky app cookie
Build Passing: https://gaautobots.atlassian.net/builds/browse/AM-AUT91
Build Passing: https://gaautobots.atlassian.net/builds/browse/AM-AST74
> AUTO-825 patch sticky app cookie header

- amazonia/classes/cf_distribution_unit.py
Passing unit tests: https://gaautobots.atlassian.net/builds/browse/AM-AUT94
> Restore OriginSSLProtocols functionality to CF distributions AUTO-845

- amazonia/classes/elb.py
- amazonia/classes/elb_listeners_config.py
- amazonia/classes/yaml_fields.py
- amazonia/defaults.yaml
- amazonia/schemas/cerberus_schema.yaml
- test/sys_tests/test_sys_autoscaling_unit.py
- test/sys_tests/test_sys_elb.py
- test/sys_tests/test_sys_zd_autoscaling_unit.py
- test/unit_tests/test_autoscaling_unit.py
- test/unit_tests/test_elb.py
- test/unit_tests/test_stack.py
- test/unit_tests/test_yaml_complete_valid.yaml
- test/unit_tests/test_zd_autoscaling_unit.py
Passing branch test: https://gaautobots.atlassian.net/builds/browse/AM-AST76-RSTWVAY-6
Passing unit tests: https://gaautobots.atlassian.net/builds/browse/AM-AUT95/latest
> Dev mettjo auto 847 app sticky cookie single value

- CHANGELOG.md
- amazonia/classes/api_gateway_unit.py
- amazonia/classes/autoscaling_unit.py
- amazonia/classes/cf_distribution_unit.py
- amazonia/classes/cf_origins_config.py
- amazonia/classes/lambda_unit.py
- amazonia/classes/stack.py
- amazonia/classes/zd_autoscaling_unit.py
- test/sys_tests/test_sys_stack.py
- test/sys_tests/test_sys_zd_autoscaling_unit.py
- test/unit_tests/test_lambda_unit.py
- test/unit_tests/test_stack.py
- test/unit_tests/test_yaml_complete_valid.yaml
Passing build: https://gaautobots.atlassian.net/builds/browse/AM-AUT96/latest
Passing build: https://gaautobots.atlassian.net/builds/browse/AM-AST77-RSTWVAY
> Add unit flow to Cloudfront distributions AUTO-849

- web/web_app.yaml
Pending Troposphere Pypi version update.
> AUTO-858 Temporarily lock web app version to v1.3.13

- CHANGELOG.md
Previous PR: https://github.com/GeoscienceAustralia/amazonia/pull/121
> AUTO-858 - Update changelog to show changes from previous PR

- amazonia/classes/amz_api_gateway.py
- amazonia/classes/amz_autoscaling.py
- amazonia/classes/amz_database.py
- amazonia/classes/amz_lambda.py
- amazonia/classes/amz_zd_autoscaling.py
- amazonia/classes/tree.py
Fix breaking unit tests
Passing build: https://gaautobots.atlassian.net/builds/browse/AM-AST80-2
> Convert exports from dict type to Troposphere Export type
